<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SarthakDell" failures="1" tests="4" name="com.automation.TestNG_RerunFailedTestCases.RediffLoginTest" time="67.210" errors="0" timestamp="2023-08-23T22:04:15 GMT-04:00" skipped="3">
  <testcase classname="com.automation.TestNG_RerunFailedTestCases.RediffLoginTest" name="loginTest" time="17.658">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="com.automation.TestNG_RerunFailedTestCases.RediffLoginTest" name="loginTest" time="18.082">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="com.automation.TestNG_RerunFailedTestCases.RediffLoginTest" name="loginTest" time="13.757">
    <failure message="Deliberately failing it" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Deliberately failing it
at org.testng.Assert.fail(Assert.java:111)
at com.automation.TestNG_RerunFailedTestCases.RediffLoginTest.loginTest(RediffLoginTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.automation.TestNG_RerunFailedTestCases.RediffLoginTest" name="loginTest" time="17.713">
    <skipped/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- com.automation.TestNG_RerunFailedTestCases.RediffLoginTest -->
